apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-gradle-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-gradle-devops
  template:
    metadata:
      labels:
        app: java-gradle-devops
    spec:
      containers:
        - name: java-app
          image: java-gradle-devops:1.0.0
          imagePullPolicy: IfNotPresent
