apiVersion: v1
kind: Service
metadata:
  name: java-gradle-devops-service
spec:
  selector:
    app: java-gradle-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
